name: build
on:
  - push
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.17.7’
      - name: Run build
        run: go build .
      - name: Run testing
        run: go test ./... --verbose
